import "../styles/globals.css";
import { Inter, Rubik, Outfit } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import type { Metadata } from "next";
import Navbar from "@/components/navbar/navbar";

const rubik = Rubik({
  variable: "--font-rubik",
});

const inter = Inter({
  variable: "--font-inter",
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop Meichu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${inter.variable} ${outfit.variable} antialiased`}
        suppressHydrationWarning
      >
        <NuqsAdapter>
          <Navbar />
          <main className="md:pb-0 pb-16 md:pt-16">{children}</main>
        </NuqsAdapter>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
