import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono, Rubik, Outfit } from "next/font/google";
import "../styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar/navbar";

const rubik = localFont({
  src: "../../public/fonts/Rubik-VariableFont_wght.ttf",
  variable: "--font-rubik",
  display: "swap",
});

const inter = localFont({
  src: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  display: "swap",
});

const arial = localFont({
  src: "../../public/fonts/arial.ttf",
  variable: "--font-arial",
  display: "swap",
});

// const rubik = Rubik({
//   variable: "--font-rubik"
// });

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shop Meichu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${inter.variable} ${arial.variable} ${outfit.variable} antialiased`}
      >
        <Navbar />
        <main className="pt-16 pb-16 sm:pb-0">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
